app:
  build: .
  volumes:
    - .:/app
  links:
    - postgres
  environment:
    - MIX_ENV=test

postgres:
  image: postgres:latest
  ports:
    - 5432
  environment:
    - POSTGRES_DB=database_name_test
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=""
